name: Update data

on:
  schedule:
    # Run at 4:25 AM UTC daily
    - cron: '25 4 * * *'
  push:
    branches:
      - main
    paths-ignore:
    - versions.json # prevent double run on JSON file update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/cache@v2 # cache dependencies
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install --production
    - name: Create JSON file
      run: yarn run create # overwrites previous file
    - name: Commit and push changes
      run: |
        git config --local user.email "mc-versions@hugmanrique.me"
        git config --local user.name "mc-versions"
        git add versions.json
        git diff --staged --quiet || { git commit -m 'Update data'; git push }

